In [ ]:
import numpy as np

In [ ]:
array = np.array([[1, 2],
                  [3, 4]])
print("2x2 Array:\n", array)

2x2 Array:
 [[1 2]
 [3 4]]


In [ ]:
random = np.random.rand(3, 4)
print("Random 3x4 array:\n", random)

Random 3x4 array:
 [[0.6234294  0.19595924 0.79054751 0.39677122]
 [0.02096715 0.79224602 0.39609878 0.65481908]
 [0.47837648 0.35900396 0.96360934 0.8231733 ]]


In [ ]:
array1 = np.ones((2, 3))
array0 = np.zeros((2, 3))
print("Array of Ones:\n", array1)
print("Array of Zeros:\n", array0)

Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
randomNum = np.random.rand(6, 3)
transpose_3x6 = randomNum.T
print("Original 6x3 Array:\n", randomNum)
print("Transposed 3x6 Array:\n", transpose_3x6)

Original 6x3 Array:
 [[0.88972469 0.83618891 0.91311731]
 [0.41077926 0.55390358 0.60733121]
 [0.38937988 0.03102969 0.91920246]
 [0.57217067 0.59482063 0.29051423]
 [0.33321949 0.45597107 0.79322695]
 [0.99503697 0.22734172 0.66647529]]
Transposed 3x6 Array:
 [[0.88972469 0.41077926 0.38937988 0.57217067 0.33321949 0.99503697]
 [0.83618891 0.55390358 0.03102969 0.59482063 0.45597107 0.22734172]
 [0.91311731 0.60733121 0.91920246 0.29051423 0.79322695 0.66647529]]


In [ ]:
n, p, m = 2, 3, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = np.dot(A, B)
print("Matrix A ({}x{}):\n".format(n,p), A)
print("Matrix B ({}x{}):\n".format(p,m), B)
print("Dot Product ({}x{}):\n".format(n,m), dot_product)

Matrix A (2x3):
 [[0.87975709 0.14293522 0.1500323 ]
 [0.95175265 0.45228387 0.96610851]]
Matrix B (3x4):
 [[0.54230156 0.81337714 0.24993382 0.99606504]
 [0.54981485 0.05886939 0.55506614 0.01721424]
 [0.59341597 0.94037098 0.86954556 0.5326268 ]]
Dot Product (2x4):
 [[0.64471311 0.86507484 0.42967947 0.95866703]
 [1.33811355 1.70925993 1.328998   1.47036855]]
